INSERT INTO RELACIONAMENTO (ID, CLIENTE, EMAIL, NOME, TRANSACAO, VALOR, PEDIDO) VALUES (null, 1, 'cliente1@techstage.io' ,'CLIENTE AMEX', 3000, 300.33,1);
INSERT INTO RELACIONAMENTO (ID, CLIENTE, EMAIL, NOME, TRANSACAO, VALOR, PEDIDO) VALUES (null, 2, 'cliente2@techstage.io' ,'CLIENTE VISA', 4000, 400.44,2);
INSERT INTO RELACIONAMENTO (ID, CLIENTE, EMAIL, NOME, TRANSACAO, VALOR, PEDIDO) VALUES (null, 3, 'cliente3@techstage.io' ,'CLIENTE MASTER', 5000, 500.55,3);
